In [1]:
#Pandas kutubxonasini import qilish

import pandas as pd

In [2]:
exam_score = pd.DataFrame([37,94,11,6,59,84,98,43,1,76,22,3,26,52,41,68,33,89,19,15,62,8,29,47,70])
exam_score

     0
0   37
1   94
2   11
3    6
4   59
5   84
6   98
7   43
8    1
9   76
10  22
11   3
12  26
13  52
14  41
15  68
16  33
17  89
18  19
19  15
20  62
21   8
22  29
23  47
24  70

In [3]:
exam_score.mean()

0    43.72
dtype: float64

In [4]:
exam_score.median()

0    41.0
dtype: float64

In [5]:
exam_score.mode()

     0
0    1
1    3
2    6
3    8
4   11
5   15
6   19
7   22
8   26
9   29
10  33
11  37
12  41
13  43
14  47
15  52
16  59
17  62
18  68
19  70
20  76
21  84
22  89
23  94
24  98

In [6]:
range_exam_score = exam_score.max() - exam_score. min()
range_exam_score

0    97
dtype: int64

In [7]:
exam_score.var()

0    915.626667
dtype: float64

In [8]:
exam_score.std()

0    30.259324
dtype: float64

In [11]:
q1_exam_score = exam_score.quantile(0.25)
q3_exam_score = exam_score.quantile(0.75)
iqr = q3_exam_score - q1_exam_score
iqr

0    49.0
dtype: float64