In [1]:
import pandas as pd

In [11]:
df = pd.read_csv ('/content/sample_data/california_housing_train.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [12]:
df['total_rooms']

0        5612.0
1        7650.0
2         720.0
3        1501.0
4        1454.0
          ...
16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 17000, dtype: float64

In [13]:
df[['population','households']]

       population  households
0          1015.0       472.0
1          1129.0       463.0
2           333.0       117.0
3           515.0       226.0
4           624.0       262.0
...           ...         ...
16995       907.0       369.0
16996      1194.0       465.0
16997      1244.0       456.0
16998      1298.0       478.0
16999       806.0       270.0

[17000 rows x 2 columns]

In [16]:
df['median_income'].iloc[0:6]

0    1.4936
1    1.8200
2    1.6509
3    3.1917
4    1.9250
5    3.3438
Name: median_income, dtype: float64

In [17]:
df[df['total_rooms']<1000]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0
21,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0
...,...,...,...,...,...,...,...,...,...
16938,-124.13,40.55,38.0,544.0,89.0,240.0,91.0,3.2500,94800.0
16944,-124.14,40.67,23.0,580.0,117.0,320.0,109.0,4.2054,130600.0
16951,-124.15,40.81,50.0,340.0,74.0,235.0,83.0,1.7500,67500.0
16969,-124.17,40.80,52.0,661.0,316.0,392.0,244.0,0.9570,60000.0
16982,-124.18,40.62,35.0,952.0,178.0,480.0,179.0,3.0536,107000.0

In [18]:
df[(df["total_rooms"]>1000)& (df["total_bedrooms"] > 100)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [19]:
df.sort_values('population')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8232,-118.44,34.04,16.0,18.0,6.0,3.0,4.0,0.5360,350000.0
2990,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.3750,137500.0
14105,-122.06,37.39,26.0,18.0,4.0,8.0,4.0,3.7500,375000.0
2907,-117.76,35.22,4.0,18.0,3.0,8.0,6.0,1.6250,275000.0
288,-116.76,34.14,4.0,42.0,10.0,9.0,3.0,0.5360,42500.0
...,...,...,...,...,...,...,...,...,...
3296,-117.87,34.04,7.0,27700.0,4179.0,15037.0,4072.0,6.6288,339700.0
2969,-117.78,34.03,8.0,32054.0,5290.0,15507.0,5050.0,6.0191,253900.0
2871,-117.74,33.89,4.0,37937.0,5471.0,16122.0,5189.0,7.4947,366300.0
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0
2274,-117.42,33.35,14.0,25135.0,4819.0,35682.0,4769.0,2.5729,134400.0

In [25]:
df.sort_values(by=['population','total_rooms'])

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8232,-118.44,34.04,16.0,18.0,6.0,3.0,4.0,0.5360,350000.0
2990,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.3750,137500.0
2907,-117.76,35.22,4.0,18.0,3.0,8.0,6.0,1.6250,275000.0
14105,-122.06,37.39,26.0,18.0,4.0,8.0,4.0,3.7500,375000.0
10911,-120.85,37.75,26.0,28.0,4.0,9.0,5.0,1.6250,85000.0
...,...,...,...,...,...,...,...,...,...
3296,-117.87,34.04,7.0,27700.0,4179.0,15037.0,4072.0,6.6288,339700.0
2969,-117.78,34.03,8.0,32054.0,5290.0,15507.0,5050.0,6.0191,253900.0
2871,-117.74,33.89,4.0,37937.0,5471.0,16122.0,5189.0,7.4947,366300.0
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0
2274,-117.42,33.35,14.0,25135.0,4819.0,35682.0,4769.0,2.5729,134400.0